seed: 42

seed: 42

trainer:
  accelerator: gpu
  max_epochs: 100
  precision: "16-mixed"
  log_every_n_steps: 20
  deterministic: true
  strategy: "ddp_find_unused_parameters_true"

data:
  root_dir: /kaggle/input/crackvarious/CRACKVARIOUS
  img_size: [256, 256]
  batch_size: 16

logger:
  save_dir: logs
  name: cafnet
  version: baseline

checkpoint:
  monitor: val_loss
  mode: max
  save_top_k: 1
  save_last: True

system:
  cudnn_benchmark: true
  matmul_precision: high

optim:
  lr: 1e-3
  weight_decay: 1e-4

model:
  selected: cafnet